spring:
  cloud:
    gateway:
      routes:
#        user-service
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - JwtAuthenticationFilter

        - id: auth-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - JwtAuthenticationFilter

        - id: roles-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/roles/**

        - id: cart-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/cart/**
          filters:
            - JwtAuthenticationFilter

        - id: white_list-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/white_list/**
          filters:
            - JwtAuthenticationFilter

        - id: address_order-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/address_order/**
          filters:
            - JwtAuthenticationFilter

        - id: blog-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/blogs/**
          filters:
            - JwtAuthenticationFilter

#        product-service
        - id: categories-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/categories/**
          filters:
            - JwtAuthenticationFilter

        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/products/**
          filters:
            - JwtAuthenticationFilter

        - id: product_image-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/product-images/**
          filters:
            - JwtAuthenticationFilter

        - id: cart_redis-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/cart/**
          filters:
            - JwtAuthenticationFilter

#        order-service
        - id: order-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - JwtAuthenticationFilter

        - id: order_detail-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/orderDetail/**
          filters:
            - JwtAuthenticationFilter

        - id: feedback-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/feedback/**
          filters:
            - JwtAuthenticationFilter

#        inventory-service
        - id: inventory-service
          uri: http://localhost:8888
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - JwtAuthenticationFilter

        - id: inventory-status-service
          uri: http://localhost:8888
          predicates:
            - Path=/api/v1/inventory_status/**
          filters:
            - JwtAuthenticationFilter

#        payment-service
        - id: payment-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/payment/**
          filters:
            - JwtAuthenticationFilter
      globals:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowCredentials: true
        csrf:
          enabled: false

  application:
    name: api-gateway

  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://localhost:8080/auth/keys

  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true


logging:
  level:
    org.springframework.web.HttpLogging: TRACE
    reactor.netty.http.server: DEBUG
    reactor.netty.http.client: DEBUG

jwt:
  jwtExpirationMs: 86400000
  secretKey: cb17bdf73fb9500c10bc64270d65efedcbdbd412c9d7a258f293e298a44dc7e5

authentication:
  enabled: true