spring:
  application:
    name: user-service

  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: password
#    url: jdbc:sqlserver://techwiz5.database.windows.net:1433;database=techwiz5-db;user=techwiz5@techwiz5;password=@Epicfigure;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:mysql://localhost:3306/epic_figures_user
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#    database-platform: org.hibernate.dialect.SQLServerDialect
  #    database-platform: org.hibernate.dialect.H2Dialect

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23li5fRSLhcmlB7nDs
            client-secret: 729963bd07baffdc0830c6a8afdbc2434ccc2892
#            redirect-uri: ${application.returnUrl}
            # scope: email, public_profile
          google:
#            client-id: 1086239543051-slijoqf2pnhskd4q2d4qg89uuod0p8cl.apps.googleusercontent.com
#            client-secret: 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
            client-id: 1086239543051-ug33jsc1pdhsaai2kna5gk69kutdd1re.apps.googleusercontent.com
            client-secret: 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
#            redirect-uri: ${application.returnUrl}

          facebook:
            client-id: 1632890864218116
            client-secret: 80be9bb154d02c8fc043624aab30c788
#            redirect-uri: ${application.returnUrl}

        resource-server:
          jwt:
            jwk-set-uri: http://localhost:8080/auth/keys

  kafka:
    producer:
        bootstrap-servers: localhost:9092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8081

logging:
  level:
    org.springframework.security: TRACE

    org.hibernate.SQL: TRACE
    org.hibernate.orm.jdbc.bind: TRACE

bezkoder:
  openapi:
    dev-url: http://localhost:8081

application:
#  jwtExpirationMs: 86400000
  returnUrl: http://localhost:8080/oauth2/redirect

jwt:
  jwtExpirationMs: 86400000
  secretKey: cb17bdf73fb9500c10bc64270d65efedcbdbd412c9d7a258f293e298a44dc7e5
  refreshKey: 5kMQSZWBxuyD0WUn3vgrRYkVY3FzfGS8eIsWAyRq5U0=
  resetKey: Q0GaCiO66seNNR8otkrpkwDo0JTYkV31Bp7uxB9ULbcw5PSO3UcMfgCCRIt5yJLv

cloudinary:
  cloud-name: dptyuisjr
  api-key: 119697286713644
  api-secret: H_SMqmlh1dz6G8FXx9sla0dt8OI

file:
  upload-logo-dir: ./uploads/logo
  upload-product-image-dir: ./uploads/productimage
  upload-user-image-dir: ./uploads/userimage
  upload-thumbnail-image-dir: ./uploads/thumbnailimage
  upload-blog-image-dir: ./uploads/blogimage

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/